### ISSUE TITLE
Issue while changing label name

### ISSUE THREAD

**Issue by manikanta1219** [LanSoSdk/LanSoEditor_advance#7]
App is not working when we change the label name in manifest.once check please

In current project label name is this one:
<string name="app_name">蓝松视频编辑专业版</string>

When we are trying to change this label the project is not working.
eg: <string name="app_name">Video Editor</string>

**Comment by LanSoSdk** [comment]
Because our professional SDK is not free, price and technical support please contact support@lansongtech.com

**Comment by LanSoSdk** [comment]
Because this version SDK is not free, price and technical support please contact support@lansongtech.com.

Our free version is as follows. Please download and use directly
https://github.com/LanSoSdk/LanSoEditor_common

**Comment by manikanta1219** [comment]
ok thanks for your information..
